#!/bin/sh
#
# OSX Terminal sources .bash_profile for all new terminal windows
# Other systems use .bash_profile for logins, .bashrc for everything else
# This unifies things, so no extra setup is needed for Mac.
#
# https://apple.stackexchange.com/a/51038
#
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
